# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pingr}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Bailey", "Sam Quigley"]
  s.date = %q{2010-06-23}
  s.description = %q{Pingr is a Ruby library for accessing the Pingdom API. It provides a thorfile so you can execute its actions from the command line.}
  s.email = %q{chris@cobaltedge.com}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    ".gitignore",
     "README.textile",
     "Rakefile",
     "Thorfile",
     "VERSION",
     "lib/PingdomAPI.rb",
     "lib/PingdomAPIDriver.rb",
     "lib/PingdomAPIMappingRegistry.rb",
     "lib/datetime_ext.rb",
     "lib/pingdom.rb"
  ]
  s.homepage = %q{http://github.com/chris/pingr}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Ruby wrapper for the Pingdom API}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

